# This is a basic workflow to help you get started with Actions

name: Publish to IPFS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ipfs-upload:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Publishes to IPFS and returns CID in  ${{ steps.ipfs.outputs.hash }}
      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.1.6
        id: ipfs
        with:
          path: ./testfolder
          host: ipfs.pollinations.ai
          port: 443
          protocol: https
          timeout: 180000
          verbose: true

